create table public."PlanoDeAula" (
  id_plano_aula bigint generated by default as identity not null,
  entrada_user json null,
  resposta_ia json null,
  titulo text null,
  introducao text null,
  objetivo_bncc text null,
  roteiro text null,
  rubrica_avaliacao text null,
  criado_em timestamp with time zone not null default now(),
  constraint PlanoDeAula_pkey primary key (id_plano_aula)
) TABLESPACE pg_default;